// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd6tsp56BECUZjmxmlIAOT8Z9yeO6xrOQ',
    appId: '1:206118908458:web:6306ddd7585b995e9a4953',
    messagingSenderId: '206118908458',
    projectId: 'my-todos-3ce52',
    authDomain: 'my-todos-3ce52.firebaseapp.com',
    storageBucket: 'my-todos-3ce52.appspot.com',
    measurementId: 'G-GWPVBN3E5M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB14-u4huKA9orVaQAJ92lNuvcZgPQuUWI',
    appId: '1:206118908458:android:4b2da9ae9ee48f669a4953',
    messagingSenderId: '206118908458',
    projectId: 'my-todos-3ce52',
    storageBucket: 'my-todos-3ce52.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaCzTc0zPgKdJ3R6MosL3HOgZO4HJHbZU',
    appId: '1:206118908458:ios:4459a456f6225fe79a4953',
    messagingSenderId: '206118908458',
    projectId: 'my-todos-3ce52',
    storageBucket: 'my-todos-3ce52.appspot.com',
    iosBundleId: 'com.example.myTodos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaCzTc0zPgKdJ3R6MosL3HOgZO4HJHbZU',
    appId: '1:206118908458:ios:4459a456f6225fe79a4953',
    messagingSenderId: '206118908458',
    projectId: 'my-todos-3ce52',
    storageBucket: 'my-todos-3ce52.appspot.com',
    iosBundleId: 'com.example.myTodos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCd6tsp56BECUZjmxmlIAOT8Z9yeO6xrOQ',
    appId: '1:206118908458:web:77ffc3a9dcb9fabf9a4953',
    messagingSenderId: '206118908458',
    projectId: 'my-todos-3ce52',
    authDomain: 'my-todos-3ce52.firebaseapp.com',
    storageBucket: 'my-todos-3ce52.appspot.com',
    measurementId: 'G-L0QVFKZY1M',
  );
}
